server:
  port: 8080

spring:
  application:
    name: mscustomer


  datasource:
    url: jdbc:h2:mem:customer
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    expiration: 30
    secret: cMOjbyBjb20gZ29pYWJhZGE

logging:
  level:
    org:
      springframework:
        security: trace
